env:
    - cc=gcc-4.8 cxx=g++-4.8 apt_packages="g++-4.8 libstdc++-4.8-dev" valgrind=true
    - cc=clang-3.3 cxx=clang++-3.3 apt_packages="clang-3.3 libstdc++-4.8-dev" valgrind=true
    - cc=clang-3.4 cxx=clang++-3.4 apt_packages="clang-3.4 libstdc++-4.8-dev" valgrind=true
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:h-rayflood/llvm -y
    - sudo apt-get update -qq
install:
    - sudo apt-get install cmake $apt_packages
    - if $valgrind; then sudo apt-get install valgrind; fi
before_script:
    - export CC="$cc" CXX="$cxx"
    - echo "$CC" && "$CC" --version
    - echo "$CXX" && "$CXX" --version
script:
    - make test $makeflags
    - if $valgrind; then make test run_with='valgrind --tool=memcheck --error-exitcode=1'; fi
    - if $valgrind; then make test run_with='valgrind --tool=helgrind --error-exitcode=1'; fi

    # Now with optimizations!
    - export CFLAGS='-O3'
    - export CXXFLAGS="$CFLAGS"
    - make clean
    - make test
    - if $valgrind; then make test run_with='valgrind --tool=memcheck --error-exitcode=1'; fi
    - if $valgrind; then make test run_with='valgrind --tool=helgrind --error-exitcode=1'; fi

    # TODO(strager): DRD (valgrind tool) crashes on vfork (posix_spawn).
